# Generated by Django 3.1 on 2021-01-02 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.JSONField()),
                ('payment_status', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('not confirmed', 'Not confirmed')], default='not confirmed', max_length=15)),
                ('payment_total', models.FloatField(default=0)),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_items_bought', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items_sell', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('current_price', models.FloatField(null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('', 'Original'), ('price changed', 'Price changed'), ('item not available', 'Item not available')], default='', max_length=18)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items_buy', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_api.item')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('price_total', models.FloatField(default=0)),
                ('pay_confirm', models.CharField(choices=[('pay', 'Pay'), ('not paid', 'Not paid')], default='not paid', max_length=15)),
                ('items', models.ManyToManyField(blank=True, to='shop_api.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
